### ISSUE TITLE
google is not defined at refreshSessionToken

### ISSUE THREAD

**Issue by sayad-mallllek** [ErrorPro/react-google-autocomplete#167]
I am using react autocomplete with session tokens and I had to use a useeffect on the main page load to add a session token because by default is comes null from usePlacesService

`  useEffect(() => {
    refreshSessionToken();
    return () => {};
  }, []);
`

  I am using Nextjs and it is giving this error
  `framework-79bce4a3a540b080.js:1 ReferenceError: google is not defined
    at refreshSessionToken (8345-36847ac2dcf11485.js:1:16048)
    at 6436-17e866bb9800252e.js:1:14460
    at Ui (framework-79bce4a3a540b080.js:1:104667)
    at t.unstable_runWithPriority (framework-79bce4a3a540b080.js:1:129355)
    at Ql (framework-79bce4a3a540b080.js:1:44986)
    at Fi (framework-79bce4a3a540b080.js:1:104128)
    at bi (framework-79bce4a3a540b080.js:1:95618)
    at framework-79bce4a3a540b080.js:1:45209
    at t.unstable_runWithPriority (framework-79bce4a3a540b080.js:1:129355)
    at Ql (framework-79bce4a3a540b080.js:1:44986)`

And it causes a client side exception

**Comment by ErrorPro** [comment]
Will check it asap

**Comment by nstanard** [comment]
This can also just happen if the google script hasn't finished loading into the global context. For instance, if you call to refresh the token on focus without checking that `google` is available in the global scope you'll probably see this.
