### ISSUE TITLE
Console warning: "Google Maps JavaScript API has been loaded directly without loading=async"

### ISSUE THREAD

**Issue by simka1911** [ErrorPro/react-google-autocomplete#232]
When using **usePlacesWidget** hook, a warning is shown in the console:

> Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance.

Is it possible to add async attribute to script during loadGoogleMapScript execution?

<img width="670" alt="google-maps-async-warning" src="https://github.com/ErrorPro/react-google-autocomplete/assets/41441484/91f424e0-77fe-44e4-8c4e-6f45dd39e1b0">

**Comment by SamLeatherdale** [comment]
The recommendations in [Google's docs on Loading the Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/overview#js_api_loader_package) don't even recommend a script tag anymore, they recommend using the [@googlemaps/js-api-loader](https://www.npmjs.com/package/@googlemaps/js-api-loader) package.

**Comment by bruno-agileengine** [comment]
It seems this issue comes from `googleMapsScriptUrl ` inside `usePlacesAutocompleteService.ts`

`export default function usePlacesAutocompleteService({
  apiKey,
  libraries = "places",
  googleMapsScriptBaseUrl = GOOGLE_MAP_SCRIPT_BASE_URL,
  debounce = 300,
  options = {},
  sessionToken,
  language,
}) {
  const languageQueryParam = language ? `&language=${language}` : "";
  **const googleMapsScriptUrl = `${googleMapsScriptBaseUrl}?key=${apiKey}&libraries=${libraries}${languageQueryParam}`;**`
  
  I tried adding the `loading=async` to `googleMapsScriptUrl` and the warning disappeared, but then I got this error
  
![image](https://github.com/ErrorPro/react-google-autocomplete/assets/128487903/05f14774-1761-4872-811d-7f8abf9a2f45)

`usePlacesAutocompleteService.js:110 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'AutocompleteService')
    at buildService (usePlacesAutocompleteService.js:110:66)
    at eval (usePlacesAutocompleteService.js:118:16)`

**Comment by malikk908** [comment]
```
const {
        placePredictions,
        getPlacePredictions,
        isPlacePredictionsLoading,
    } = usePlacesService({
        apiKey: `${process.env.REACT_APP_MAPS_API_KEY}&loading=async` ,
        debounce: 500
    });
```
    
this solved the issue for me

**Comment by lizhenew** [comment]
> ```
> const {
>         placePredictions,
>         getPlacePredictions,
>         isPlacePredictionsLoading,
>     } = usePlacesService({
>         apiKey: `${process.env.REACT_APP_MAPS_API_KEY}&loading=async` ,
>         debounce: 500
>     });
> ```
> 
> I am using `usePlacesAutocompleteService` but you may try on `usePlacesWidget` as well.
> This solved the issue for me.

I tried this method:
```
apiKey: `${apiKey}&loading=async`, 
```
but it will cause other errors. 😢 
<img width="911" alt="Screenshot 2024-06-05 at 14 30 34" src="https://github.com/ErrorPro/react-google-autocomplete/assets/126143602/eedc23b3-7b25-45a2-8e75-8799987d3aa1">

**Comment by malikk908** [comment]
> > ```
> > const {
> >         placePredictions,
> >         getPlacePredictions,
> >         isPlacePredictionsLoading,
> >     } = usePlacesService({
> >         apiKey: `${process.env.REACT_APP_MAPS_API_KEY}&loading=async` ,
> >         debounce: 500
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am using `usePlacesAutocompleteService` but you may try on `usePlacesWidget` as well.
> > This solved the issue for me.
> 
> I tried this method:
> 
> ```
> apiKey: `${apiKey}&loading=async`, 
> ```
> 
> but it will cause other errors. 😢 <img alt="Screenshot 2024-06-05 at 14 34 36" width="540" src="https://private-user-images.githubusercontent.com/126143602/336714616-07968f5b-e905-4467-b991-b3398c1e6b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1Njk4ODEsIm5iZiI6MTcxNzU2OTU4MSwicGF0aCI6Ii8xMjYxNDM2MDIvMzM2NzE0NjE2LTA3OTY4ZjViLWU5MDUtNDQ2Ny1iOTkxLWIzMzk4YzFlNmI0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwNjM5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGNlZTIwN2FmNTBmZWIzNGFmNWY4NmFiN2RjMzUwMmExZGY4ZDBjZDI1YTcyMTZhYWM0OTMwNDJjZmEwOTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m9b04A8RZyF0lwbTOWNtLYbGfr8OOMyNMhouGQoT4Co">

are you trying to display multiple instances of usePlaceService in the same page/component ? because thats the same error I got, I created an issue and the possible workaround, please go through it

**Comment by lizhenew** [comment]
> > 
> > 
> > I tried this method:
> > ```
> > apiKey: `${apiKey}&loading=async`, 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but it will cause other errors. 😢 <img alt="Screenshot 2024-06-05 at 14 34 36" width="540" src="https://private-user-images.githubusercontent.com/126143602/336714616-07968f5b-e905-4467-b991-b3398c1e6b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1Njk4ODEsIm5iZiI6MTcxNzU2OTU4MSwicGF0aCI6Ii8xMjYxNDM2MDIvMzM2NzE0NjE2LTA3OTY4ZjViLWU5MDUtNDQ2Ny1iOTkxLWIzMzk4YzFlNmI0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwNjM5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGNlZTIwN2FmNTBmZWIzNGFmNWY4NmFiN2RjMzUwMmExZGY4ZDBjZDI1YTcyMTZhYWM0OTMwNDJjZmEwOTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m9b04A8RZyF0lwbTOWNtLYbGfr8OOMyNMhouGQoT4Co">
> 
> are you trying to display multiple instances of usePlaceService in the same page/component ? because thats the same error I got, I created an issue and the possible workaround, please go through it #236

Maybe it's different from your situation, I still encounter this issue when only use one AutoComplete component in page.
Then I used the method you provided in [ #236](https://github.com/ErrorPro/react-google-autocomplete/issues/236). Indeed, the previous `undefined (reading 'AutocompleteService')`  issue have been resolved, but the component will encounter another new issue on the first input. 😭 
<img width="805" alt="Screenshot 2024-06-05 at 15 04 51" src="https://github.com/ErrorPro/react-google-autocomplete/assets/126143602/43de4704-5cb4-4efd-9260-6d61ecb20df2">

**Comment by malikk908** [comment]
> > > I tried this method:
> > > ```
> > > apiKey: `${apiKey}&loading=async`, 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > but it will cause other errors. 😢 <img alt="Screenshot 2024-06-05 at 14 34 36" width="540" src="https://private-user-images.githubusercontent.com/126143602/336714616-07968f5b-e905-4467-b991-b3398c1e6b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1Njk4ODEsIm5iZiI6MTcxNzU2OTU4MSwicGF0aCI6Ii8xMjYxNDM2MDIvMzM2NzE0NjE2LTA3OTY4ZjViLWU5MDUtNDQ2Ny1iOTkxLWIzMzk4YzFlNmI0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwNjM5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGNlZTIwN2FmNTBmZWIzNGFmNWY4NmFiN2RjMzUwMmExZGY4ZDBjZDI1YTcyMTZhYWM0OTMwNDJjZmEwOTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m9b04A8RZyF0lwbTOWNtLYbGfr8OOMyNMhouGQoT4Co">
> > 
> > 
> > are you trying to display multiple instances of usePlaceService in the same page/component ? because thats the same error I got, I created an issue and the possible workaround, please go through it #236
> 
> Maybe it's different from your situation, I still encounter this issue when only use one AutoComplete component in page. Then I used the method you provided in [ #236](https://github.com/ErrorPro/react-google-autocomplete/issues/236). Indeed, the previous `undefined (reading 'AutocompleteService')` issue have been resolved, but the component will encounter another new issue. 😭 <img alt="Screenshot 2024-06-05 at 15 04 51" width="805" src="https://private-user-images.githubusercontent.com/126143602/336727299-43de4704-5cb4-4efd-9260-6d61ecb20df2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzcwMDMsIm5iZiI6MTcyMDE3NjcwMywicGF0aCI6Ii8xMjYxNDM2MDIvMzM2NzI3Mjk5LTQzZGU0NzA0LTVjYjQtNGVmZC05MjYwLTZkNjFlY2IyMGRmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxMDUxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGQ5NTIyMjhjZWMxYzg1ODc1NzllNWNiNWUwMzAyZDZmNTFlNzY4NGRiMzRkZGQxYTQ2YmMyMjkyZTJkZmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PZYhV4YDjCtaFc7idud9fvc3O46TssrIIjrHlOJyZ78">

sorry for late reply, however I have also noticed the same error in my app but my Autocomplete component works fine so I this isn't bothering me much.

**Comment by nseokaneJHB** [comment]
> &loading=async

Used th

> ```
> const {
>         placePredictions,
>         getPlacePredictions,
>         isPlacePredictionsLoading,
>     } = usePlacesService({
>         apiKey: `${process.env.REACT_APP_MAPS_API_KEY}&loading=async` ,
>         debounce: 500
>     });
> ```
> 
> I am using `usePlacesAutocompleteService` but you may try on `usePlacesWidget` as well.
> 
> This solved the issue for me.

This resolved the issue for me
